stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
      url: git@github.com:Half-Void/seed.git
- name: Build
  steps:
  - runScriptConfig:
      image: test/hello
      shellScript: |-
        mkdir -p /test/
        ln -s `pwd` /test
        cd /test
        docker build -t test/hello .
        docker images
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
