stages:
- name: run a script
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: ls
- name: pushu image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myproject/hello-world:v1.0
      pushRemote: true
      registry: 192.168.55.100:80
    env:
      PLUGIN_DEBUG: true
      PLUGIN_INSECURE: true
timeout: 60
notification: {}
