name: case07
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
      sourceCodeCredentialId: user-2dv5r:c-hkr6b-github-half-void
      url: https://github.com/Half-Void/seed.git
- name: build
  steps:
  - runScriptConfig:
      image: busybox:latest
      isShell: true
      shellScript: ls
- name: publish
  steps:
  - publishImageConfig:
      buildContext: .
      dockerfilePath: ./Dockerfile
      tag: pipeline/build:${CICD_PIPELINE_ID}
