stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
      url: git@github.com:Half-Void/seed.git
#- name: Build
#  steps:
#  - runScriptConfig:
#      image: test/hello
#      shellScript: 
#        mkdir -p /test/
#        ln -s `pwd` /test
#        cd /test
#        docker build -t test/hello .
#        docker images
- name: Build
  steps:
  - runScriptConfig:
      image: test/hello
      isShell: true
      shellScript: ls
- name: publish
  steps:
  - publishImageConfig:
      buildContext: .
      dockerfilePath: ./Dockerfile
      tag: pipeline/build:${CICD_PIPELINE_ID}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml

